### ISSUE TITLE
From zero to one: Project init

### ISSUE THREAD

**Issue by JuanitoFatas** [rubytaiwan/rubytw-reboot#1]
- Init Rails 4.2.4 project
- Application name: `rubytw-reboot`
- Change README.rdoc to README.md
- Database: PostgreSQL
- Markup: Slim

@AnNOtis If you have any questions can ask me! Thanks :bow: 

/cc @rubytaiwan/rubyists

**Comment by AnNOtis** [comment]
Check it out. :wink:

**Comment by JuanitoFatas** [comment]
Nice! :confetti_ball: :clap: :tada:
