### ISSUE TITLE
Make Code of Conduct a static page

### ISSUE THREAD

**Issue by JuanitoFatas** [rubytaiwan/rubytw-reboot#39]
Use kramdown.
https://github.com/slim-template/slim#embedded-engines-markdown-

**Comment by azi** [comment]
put this page under docs?

**Comment by JuanitoFatas** [comment]
Put here `/code-of-conduct` 😊 Thanks!

**Comment by azi** [comment]
got it , thanks :+1:

**Comment by JuanitoFatas** [comment]
Implemented in #46.
