### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by JuanitoFatas** [rubytaiwan/rubytw-reboot#7]
- [x] .travis.yml
- [x] we only need to test Ruby 2.1.x and 2.2.x and ruby-head (but allow it to fail)
- [x] svg badge

**Comment by puff-tw** [comment]
Note : Travis CI require admin rights.

**Comment by JuanitoFatas** [comment]
> Note : Travis CI require admin rights.

Enabled. Now you can follow [this guide](http://docs.travis-ci.com/user/languages/ruby/) to set it up, thanks!

**Comment by puff-tw** [comment]
svg badge paste to README.md

```
[![Build Status](https://travis-ci.org/rubytaiwan/rubytw-reboot.svg?branch=master)](https://travis-ci.org/rubytaiwan/rubytw-reboot)
```
